apiVersion: v1
kind: Service
metadata:
  name: java-internship-user-service
  labels:
    app: java-internship-user-service
spec:
  selector:
    app: java-internship-user-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
  